export const BLOCK_WIDTH = 32;
export const PLAYERBAR_HEIGHT = 26;
export const TOOLBAR_HEIGHT = PLAYERBAR_HEIGHT + 6;
export const RECOVERY_FRAME = [19, 24, 28, 31, 34, 37, 40, 42, 44, 46, 48];
export const STATE_IDLE = 'STATE_IDLE';
export const STATE_END = 'STATE_END';
export const STATE_PLAY = 'STATE_PLAY';
export const STATE_STEP = 'STATE_STEP';
export const STATE_RESET = 'STATE_RESET';
